#!/usr/bin/env php
<?php

/**
 * .git/hooks/pre-commit
 *
 * This pre-commit hooks will check for PHP errors (lint), and make sure the
 * code is PSR-2 compliant.
 */
class PreCommitChecks
{
    private bool $error = false;

    public function run(): int
    {
        $this->writeln();
        $this->writeln('Checking commit requirements', 0);
        $this->writeln();

        if ($this->isRebase()) {
            echo 'Not on branch' . PHP_EOL;

            return 0;
        }

        $this->runPhpLint($this->getCommittedFileList());
        $this->runPhpCsFixer($this->getCommittedFileList());
        $this->runPHPStan($this->getCommittedFileList());
        $this->runEsLint($this->getCommittedFileList('js'));

        if ($this->error) {
            $this->writeln("If you are ABSOLUTELY sure your code is correct, you can use 'git commit --no-verify' to bypass this validation", 0);
        }

        exit((int) $this->error);
    }

    private function writeln(string $output = '', int $level = 1): void
    {
        $this->write($output, $level);
        echo PHP_EOL;
    }

    private function write(string $output = '', int $level = 1): void
    {
        $spaces = $level * 3;

        echo str_pad($output, strlen($output) + $spaces, ' ', STR_PAD_LEFT);
    }

    private function isRebase(): bool
    {
        $output = [];
        exec('git symbolic-ref --short -q HEAD', $output);

        return empty($output);
    }

    /**
     * @param string $extension
     * @return string[]
     */
    private function getCommittedFileList(string $extension = 'php'): array
    {
        exec("git diff --name-only --diff-filter=ACMRTUXB \"HEAD\" | grep -e '\." . $extension . "$'", $fileList);

        return $fileList;
    }

    private function runPhpLint(array $fileList): void
    {
        $this->writeln('# Checking php syntax');
        $this->writeln('> php -l');

        foreach ($fileList as $file) {
            exec('php -l ' . escapeshellarg($file) . ' 2> /dev/null', $output, $return);
            if ($return !== 0) {
                $this->writeln('- ' . $output[1], 2);
                $this->error = true;
            }
        }

        $this->writeln();
    }

    private function runPhpCsFixer(array $fileList): void
    {
        $this->writeln('# Checking php code style');
        $this->writeln('> php-cs-fixer fix -v --no-ansi --dry-run');

        if (!$this->isPHPCSFixerAvailable()) {
            $this->error = true;
            $this->writeln('- php-cs-fixer is NOT installed. Please install composer with dev dependencies.', 2);
            $this->writeln();

            return;
        }

        foreach ($fileList as $file) {
            exec('./../../../../../../vendor/bin/php-cs-fixer fix -v --no-ansi --dry-run ' . escapeshellarg($file) . ' 2>&1', $output, $return);

            if ($return !== 0) {
                $this->writeln('- ' . preg_replace('#^(\s+)?\d\)\s#', '', $output[3]), 2);
                $fixes[] = './../../../../../../vendor/bin/php-cs-fixer fix -v ' . escapeshellarg($file);
                $this->error = true;
            }
        }

        if (!empty($fixes)) {
            $this->writeln();
            $this->writeln('Help:', 2);
            foreach ($fixes as $fix) {
                $this->writeln($fix, 3);
            }
        }

        $this->writeln();
    }

    private function runPHPStan(array $fileList): void
    {
        $this->writeln('# Checking code with PHPStan');
        $this->writeln('> phpstan analyse');
        $this->writeln();

        if ($fileList === []) {
            return;
        }

        if (!$this->isPHPStanAvailable()) {
            $this->writeln('- PHPStan is NOT installed. Please install composer with dev dependencies or use higher Shopware version.', 2);
            $this->writeln();

            return;
        }

        exec('./../../../../../../vendor/bin/phpstan analyse .', $output, $return);
        if ($return !== 0) {
            $this->error = true;
            $this->writeln('> PHPStan errors found');
        }

        $this->writeln();
    }

    private function runEsLint(array $fileList): void
    {
        $this->writeln('# Checking javascript code style');
        $this->writeln('> eslint.js --ignore-path .eslintignore');

        if (!$this->isESLintAvailable()) {
            $this->writeln('- eslint.js not found. Skipping javascript code style check.', 2);
            $this->writeln();

            return;
        }

        $this->checkESLint($fileList);

        $this->writeln();
    }

    public function isPHPCSFixerAvailable(): bool
    {
        return is_executable('./../../../../../../vendor/bin/php-cs-fixer');
    }

    private function isPHPStanAvailable(): bool
    {
        return is_executable('./../../../../../../vendor/bin/phpstan');
    }

    public function isESLintAvailable(): bool
    {
        return is_executable('./../../../../../../themes/node_modules/eslint/bin/eslint.js');
    }

    private function checkESLint(array $fileList = []): void
    {
        $output = [];
        $return = 0;
        exec(
            './../../../../../../themes/node_modules/eslint/bin/eslint.js ' .
            '--ignore-path .eslintignore ' .
            '-c ./../../../../../../themes/.eslintrc.js ' .
            '--global "Ext" ' .
            implode(' ', $fileList),
            $output,
            $return
        );
        $return = !(bool) $return;

        if (!$return) {
            $this->error = true;

            foreach ($output as $line) {
                $this->writeln($line, 2);
            }

            $this->writeln('Help:', 2);
            $this->writeln(
                './../../../../../../themes/node_modules/eslint/bin/eslint.js ' .
                '--fix --ignore-path .eslintignore ' .
                '-c ./../../../../../../themes/.eslintrc.js ' .
                '--global "Ext" ' .
                implode(' ', $fileList),
                3
            );
        }
    }
}

$checks = new PreCommitChecks();
$checks->run();
